'use client';
import {apiFetch,signIn,signOut,apiBase} from './lib/transport';
import {useState,useEffect,useMemo,useRef,useCallback,Fragment} from 'react';
import {BookOpen,Grid2X2,Search,Plus,ArrowUpRight,MapPin,Download,RefreshCw,Check,X,LogIn,Pencil,ExternalLink} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {PublisherImport} from '@/components/publisher-import';
import {CoverPicker} from '@/components/cover-picker';
import {Checkbox} from '@/components/ui/checkbox';
import publisherCandidates from "@/data/catalog-supplement.json";
import type {Book,Edition} from '@/lib/books';
import {normalize,dateLabel,blankBook} from '@/lib/books';

type Catalog={candidates:Edition[];warnings:string[]};
const responses=new Map<string,Promise<Catalog>>();
function lookup(b:Pick<Book,'title'|'author'|'publisher'|'isbn'>,refresh=false){
 const key=[b.title,b.author,b.publisher,b.isbn].join('|');
 if(refresh)responses.delete(key);
 if(!responses.has(key))responses.set(key,apiFetch('/api/editions?'+new URLSearchParams({title:b.title,author:b.author,publisher:b.publisher,isbn:b.isbn,...(refresh?{refresh:'1'}:{})})).then(async r=>{const d=await r.json() as Catalog & {error:string};if(!r.ok)throw Error(d.error);return d}).catch(e=>{responses.delete(key);throw e}));
 return responses.get(key)!;
}
function Cover({book,suggested}:{book:Book;suggested?:Edition}){
 const [failed,setFailed]=useState(false);const url=book.coverUrl||suggested?.coverUrl||'';
 useEffect(()=>setFailed(false),[url]);
 return <div className="cover-wrap">{url&&!failed?<img src={url} alt={'Portada de '+book.title} loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>:<div className="cover-placeholder"><BookOpen aria-hidden="true"/><span>{book.title}</span><small>{book.author}</small></div>}
 {(!url||failed)?<span className="cover-label">Portada no disponible</span>:book.coverStatus!=='confirmed'&&<span className="cover-label">Portada orientativa</span>}</div>
}
function Filter({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:[string,string][]}){
 return <Select value={value} onValueChange={onChange}><SelectTrigger className="filter" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select>
}
function Field({label,value,onChange,type='text',wide=false}:{label:string;value:string;onChange:(v:string)=>void;type?:string;wide?:boolean}){
 return <label className={'field'+(wide?' wide':'')}><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} maxLength={type==='url'?2048:500}/></label>
}
function Editor({initial,canEdit,onSaved,onClose,suggested,startEditing}:{initial:Book;canEdit:boolean;onSaved:(b:Book)=>void;onClose:()=>void;suggested?:Edition;startEditing:boolean}){
 const [draft,setDraft]=useState<Book>({...initial});const [editing,setEditing]=useState(startEditing);const [catalog,setCatalog]=useState<Catalog|null>(null);const [searching,setSearching]=useState(false);const [searchError,setSearchError]=useState('');const [error,setError]=useState('');const [saving,setSaving]=useState(false);const [dirty,setDirty]=useState(false);const [searched,setSearched]=useState('');const [allPublishers,setAllPublishers]=useState(false);
 const [showSearch,setShowSearch]=useState(initial.editionStatus==='pending');const [manual,setManual]=useState(initial.editionStatus==='none');const [showDiscard,setShowDiscard]=useState(false);
 const searchRun=useRef(0);
 const patch=(fields:Partial<Book>)=>{setDraft(d=>{const sources={...d.metadataSources};if(!fields.metadataSources)for(const key of Object.keys(fields))delete sources[key as keyof typeof sources];return {...d,...fields,metadataSources:fields.metadataSources??sources}});setDirty(true)};
 const identityField=(name:'title'|'author'|'publisher',value:string)=>{patch({[name]:value,editionStatus:'pending',editionId:'',editionSource:'',coverUrl:'',coverSource:'',publisherUrl:'',metadataSources:{},coverStatus:'missing',isbn:'',editionYear:'',language:'',translator:'',pages:'',originalYear:'',workSource:''});setShowSearch(true);setManual(false)};
 async function search(refresh=false){
  if(draft.title.trim().length<2&&!draft.isbn)return;
  const run=++searchRun.current;setSearching(true);setSearchError('');setCatalog(null);
  try{const data=await lookup(draft,refresh);if(run!==searchRun.current)return;setCatalog(data);setSearched(draft.publisher);setAllPublishers(false)}catch(e){if(run===searchRun.current)setSearchError((e as Error).message)}finally{if(run===searchRun.current)setSearching(false)}
 }
 useEffect(()=>{if(!showSearch)return;const timer=setTimeout(()=>{void search()},700);return()=>{clearTimeout(timer);searchRun.current++}},[draft.title,draft.author,draft.publisher,draft.isbn,showSearch]);
 useEffect(()=>{if(!dirty)return;const handler=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler)},[dirty]);
 const close=()=>{if(dirty)setShowDiscard(true);else onClose()};
 const selectedEdition=(e:Edition)=>{patch({author:e.author||draft.author,publisher:e.publisher||draft.publisher,isbn:e.isbn,editionYear:e.year,language:e.language,pages:e.pages,translator:e.translator,coverUrl:e.coverUrl,coverSource:'',coverStatus:e.coverUrl?'confirmed':'missing',editionStatus:'confirmed',editionId:e.id,editionSource:e.source,originalYear:e.originalYear,originalTitle:e.originalTitle,workSource:e.workSource});setShowSearch(false);setManual(false);setEditing(true)};
 async function save(){
  if(!draft.title.trim()){setError('Escriu el títol del llibre.');return}
  setSaving(true);setError('');
  try{const r=await apiFetch('/api/books',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const d=await r.json() as {error:string;book:Book};if(!r.ok)throw Error(d.error);setDirty(false);onSaved(d.book)}catch(e){setError((e as Error).message)}finally{setSaving(false)}
 }
 const matching=(catalog?.candidates??[]).filter(e=>{const p=normalize(searched),ep=normalize(e.publisher);return p&&ep&&(ep.includes(p)||p.includes(ep))});
 const candidates=allPublishers||matching.length===0?(catalog?.candidates??[]):matching;
 return <Dialog open onOpenChange={open=>{if(!open&&!saving)close()}}><DialogContent className="book-dialog" showCloseButton={false} onEscapeKeyDown={e=>{e.preventDefault();if(!saving)close()}} onPointerDownOutside={e=>{e.preventDefault();if(!saving)close()}}>
 <button aria-label="Tanca la fitxa" className="close-dialog" onClick={close} disabled={saving}><X size={20}/></button>
 <div className="dialog-intro"><p className="eyebrow">{initial.version===0?'NOVA LECTURA':'EL MEU QUADERN'}</p><DialogTitle className="dialog-title">{editing?(initial.version===0?'Afegir un llibre':'Editar la lectura'):draft.title}</DialogTitle><DialogDescription className="muted">{editing?'Les dades i els records es desaran quan premis «Desa la lectura».':draft.author||'Autor pendent'}</DialogDescription></div>
 {showDiscard?<div className="notice"><p>Tens canvis sense desar. Vols continuar editant o descartar-los?</p><div className="actions" style={{marginTop:12}}><button className="primary" onClick={()=>setShowDiscard(false)}>Continua editant</button><button className="secondary" onClick={onClose}>Descarta els canvis</button></div></div>:null}
 {!editing?<><div className="detail-grid"><div className="detail-cover"><Cover book={draft} suggested={suggested}/>{draft.editionStatus==='confirmed'?<span className="tag"><Check size={13}/> Edició confirmada</span>:<span className="tag">{draft.editionStatus==='none'?'Edició no trobada':'Edició per confirmar'}</span>}</div><div><dl><div><dt>Lectura</dt><dd>{draft.read?dateLabel(draft.finishedOn):'Encara no marcat com a llegit'}</dd></div><div><dt>Lloc</dt><dd>{draft.place||'—'}</dd></div><div><dt>Editorial</dt><dd>{draft.publisher||'—'}</dd></div><div><dt>Any de l’edició</dt><dd>{draft.editionYear||'Pendent de confirmar'}</dd></div><div><dt>Primera publicació de l’obra</dt><dd>{draft.originalYear||'Pendent de documentar'}</dd></div><div><dt>ISBN de l’edició</dt><dd>{draft.isbn||'Pendent'}</dd></div>{draft.originalTitle&&<div><dt>Títol original</dt><dd>{draft.originalTitle}</dd></div>}{draft.language&&<div><dt>Idioma</dt><dd>{draft.language}</dd></div>}{draft.pages&&<div><dt>Pàgines</dt><dd>{draft.pages}</dd></div>}{draft.translator&&<div><dt>Traducció</dt><dd>{draft.translator}</dd></div>}{draft.recordedYear&&<div><dt>Any anotat a l’Excel</dt><dd>{draft.recordedYear}</dd></div>}{draft.editionSource&&<div className="full"><a className="link" href={draft.editionSource} target="_blank" rel="noreferrer">Fitxa de l’edició al catàleg ↗</a></div>}{draft.publisherUrl&&<div className="full"><a className="link" href={draft.publisherUrl} target="_blank" rel="noreferrer">Fitxa oficial de l’editorial ↗</a></div>}{draft.coverSource&&<div className="full"><a className="link" href={draft.coverSource} target="_blank" rel="noreferrer">Font de la portada ↗</a></div>}{draft.workSource&&<div className="full"><a className="link" href={draft.workSource} target="_blank" rel="noreferrer">Font de la primera publicació ↗</a></div>}</dl></div></div><div className="personal-note"><h3>El meu record</h3><p>{draft.summary||'Encara no hi ha cap record escrit.'}</p></div>{canEdit&&<div className="actions" style={{marginTop:15}}><button className="primary" onClick={()=>setEditing(true)}><Pencil size={16}/>Edita la lectura</button>{!showSearch&&<button className="secondary" onClick={()=>setShowSearch(true)}>Cerca una altra edició</button>}</div>}</>:<form onSubmit={e=>{e.preventDefault();void save()}}>
 <div className="field-grid editor-top"><Field label="Títol *" value={draft.title} onChange={v=>identityField('title',v)} wide/><Field label="Autor" value={draft.author} onChange={v=>identityField('author',v)}/><Field label="Editorial que vas llegir" value={draft.publisher} onChange={v=>identityField('publisher',v)}/></div>
 <h3 className="form-section">La meva lectura</h3><div className="field-grid"><label className="checkbox-field"><Checkbox checked={draft.read} onCheckedChange={v=>patch({read:v===true})}/>Ja l’he llegit</label><div/><Field label="Dia que el vaig acabar" type="date" value={draft.finishedOn} onChange={v=>patch({finishedOn:v})}/><Field label="Lloc" value={draft.place} onChange={v=>patch({place:v})}/><label className="field wide">El meu resum o record<textarea value={draft.summary} maxLength={40000} onChange={e=>patch({summary:e.target.value})} placeholder="Què en vols recordar?"/></label></div>
 {draft.editionStatus==='confirmed'&&<div className="notice" style={{marginTop:20}}><Check size={16} style={{display:'inline',marginRight:6}}/>Edició seleccionada: {draft.publisher} · {draft.editionYear||'any no disponible'} · ISBN {draft.isbn||'no disponible al catàleg'}<button type="button" className="text-button" onClick={()=>setShowSearch(true)}>Canvia l’edició</button></div>}
 {(draft.editionStatus==='confirmed'||manual||!!draft.publisherUrl)&&<><h3 className="form-section">Dades de l’obra i l’edició</h3><div className="field-grid"><Field label="ISBN de l’edició" value={draft.isbn} onChange={v=>patch({isbn:v})}/><Field label="Any de l’edició" value={draft.editionYear} onChange={v=>patch({editionYear:v})}/><Field label="Primera publicació de l’obra" value={draft.originalYear} onChange={v=>patch({originalYear:v})}/><Field label="Títol original" value={draft.originalTitle} onChange={v=>patch({originalTitle:v})}/><Field label="Idioma" value={draft.language} onChange={v=>patch({language:v})}/><Field label="Traductor/a" value={draft.translator} onChange={v=>patch({translator:v})}/><Field label="Pàgines" value={draft.pages} onChange={v=>patch({pages:v})}/>{manual&&<Field label="Font de les dades de l’edició (HTTPS)" type="url" value={draft.editionSource} onChange={v=>patch({editionSource:v})} wide/>}</div></>}
 <PublisherImport book={draft} onLink={url=>patch({publisherUrl:url})} onApply={fields=>{patch(fields);setManual(true)}}/>
 <CoverPicker value={draft.coverUrl} onPick={(url,page)=>patch({coverUrl:url,coverSource:page,coverStatus:url?'confirmed':'missing'})}/>
 </form>}
 {showSearch&&<section className="edition-area"><div className="actions" style={{justifyContent:'space-between'}}><h3 className="form-section">Quina edició vas llegir?</h3><button className="text-button" onClick={()=>void search(true)} disabled={searching||draft.title.trim().length<2}><RefreshCw size={15}/>Torna a cercar</button></div><p className="muted">La cerca és automàtica. Compara l’editorial, l’any i la portada abans de triar.</p>
 {searching&&<p className="notice" role="status" style={{marginTop:15}}>Cercant edicions als catàlegs i a les editorials…</p>}
 {searchError&&<p className="notice error" role="alert" style={{marginTop:15}}>{searchError}</p>}
 {catalog?.warnings.map(w=><p key={w} className="small-note">{w}</p>)}
 {catalog&&!searching&&<><div className="statusline"><span>{matching.length&&!allPublishers?matching.length+' opcions de l’editorial indicada':candidates.length+' possibles edicions'}</span>{matching.length>0&&!allPublishers&&<button className="text-button" onClick={()=>setAllPublishers(true)}>Mostra també altres editorials</button>}</div>{!matching.length&&searched&&candidates.length>0&&<p className="small-note">No hem trobat una coincidència amb «{searched}». Aquestes són alternatives per revisar.</p>}
 <div className="edition-grid">{candidates.map(e=><article className="edition-card" key={e.id}>{e.coverUrl?<img src={e.coverUrl} alt={'Portada: '+e.title} loading="lazy" referrerPolicy="no-referrer" onError={ev=>{ev.currentTarget.style.visibility='hidden'}}/>:<BookOpen size={40} aria-hidden="true"/>}<div><h3>{e.title}</h3><p>{e.author}</p><p><strong>{e.publisher||'Editorial no indicada'}</strong> · {e.year||'Any no indicat'}</p><p>{e.language||'Idioma no indicat'}{e.pages?' · '+e.pages+' pàgines':''}</p><p>ISBN: {e.isbn||'No disponible'}</p><a className="catalog-link link" href={e.source} target="_blank" rel="noreferrer">Consulta la fitxa ↗</a></div>{canEdit&&<button className="secondary" onClick={()=>selectedEdition(e)}><Check size={15}/>És aquesta edició</button>}</article>)}</div>
 {!candidates.length&&<p className="notice">No s’han trobat edicions. Pots ajustar el títol o l’editorial, reintentar-ho o completar les dades manualment.</p>}</>}
 {canEdit&&<button className="secondary" onClick={()=>{patch({editionStatus:'none',editionId:'',editionSource:'',isbn:'',editionYear:'',language:'',translator:'',pages:'',coverUrl:'',coverSource:'',coverStatus:'missing'});setManual(true);setShowSearch(false);setEditing(true)}}>Cap d’aquestes · completar manualment</button>}
 </section>}
 {error&&<p className="notice error" role="alert">{error}</p>}
 <div className="dialog-bottom">{editing&&canEdit?<><button className="secondary" disabled={saving} onClick={close}>Cancel·la</button><button className="primary" disabled={saving||!draft.title.trim()} onClick={()=>void save()}>{saving?'Desant…':'Desa la lectura'}</button></>:<button className="secondary" onClick={close}>Tanca</button>}</div>
 </DialogContent></Dialog>
}
export default function Library({initialBooks}:{initialBooks:Book[]}){
 const [books,setBooks]=useState(initialBooks);const [loaded,setLoaded]=useState(false);const [canEdit,setCanEdit]=useState(false);const [signedIn,setSignedIn]=useState(false);const [view,setView]=useState('library');const [query,setQuery]=useState('');const [status,setStatus]=useState('read');const [year,setYear]=useState('all');const [sort,setSort]=useState('recent');const [limit,setLimit]=useState(24);const [active,setActive]=useState<Book|null>(null);const [startEditing,setStartEditing]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [suggestions,setSuggestions]=useState<Record<string,Edition>>(()=>Object.fromEntries(initialBooks.flatMap(b=>{const e=publisherCandidates.find(e=>e.coverUrl&&e.matchTitles?.some(t=>normalize(t)===normalize(b.title)));return e?[[b.id,e as Edition]]:[]})));const [coverProgress,setCoverProgress]=useState(false);
 const attempted=useRef(new Set<string>());const activeRef=useRef(active);activeRef.current=active;
 const load=useCallback(async()=>{try{const r=await apiFetch('/api/books');const d=await r.json() as {error:string;books:Book[];canEdit:boolean;signedIn:boolean};if(!r.ok)throw Error(d.error);setBooks(d.books);setSuggestions(current=>({...Object.fromEntries(d.books.flatMap(b=>{const e=publisherCandidates.find(e=>e.coverUrl&&e.matchTitles?.some(t=>normalize(t)===normalize(b.title)));return e?[[b.id,e as Edition]]:[]})),...current}));setCanEdit(d.canEdit);setSignedIn(d.signedIn);setLoaded(true);setError('')}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{void load();const refresh=()=>{if(!activeRef.current)void load()};window.addEventListener('focus',refresh);const timer=setInterval(()=>{if(document.visibilityState==='visible')refresh()},30000);return()=>{window.removeEventListener('focus',refresh);clearInterval(timer)}},[load]);
 useEffect(()=>{setLimit(24)},[query,year,status,sort]);
 const years=useMemo(()=>Array.from(new Set(books.map(b=>b.finishedOn.slice(0,4)).filter(Boolean))).sort().reverse(),[books]);
 const filtered=useMemo(()=>books.filter(b=>(status==='all'||status==='read'&&b.read||status==='unread'&&!b.read||status==='pending'&&b.editionStatus!=='confirmed')&&(year==='all'||b.finishedOn.startsWith(year))&&normalize([b.title,b.author,b.publisher,b.summary,b.place,b.isbn].join(' ')).includes(normalize(query))).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title,'ca'):sort==='oldest'?a.finishedOn.localeCompare(b.finishedOn):b.finishedOn.localeCompare(a.finishedOn)),[books,status,year,query,sort]);
 const visible=filtered.slice(0,limit);
 useEffect(()=>{if(!loaded)return;let cancelled=false;async function covers(){setCoverProgress(true);for(const b of visible){if(cancelled)break;const key=[b.id,b.title,b.author,b.publisher].join('|');if(b.coverUrl||b.editionStatus==='none'||attempted.current.has(key))continue;attempted.current.add(key);try{const r=await lookup(b);const e=r.candidates.find(e=>e.coverUrl&&e.score>=35);if(e&&!cancelled)setSuggestions(s=>({...s,[b.id]:e}));}catch{}await new Promise(r=>setTimeout(r,1100))}if(!cancelled)setCoverProgress(false)}void covers();return()=>{cancelled=true}},[loaded,filtered,limit]);
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();const register=(tool:unknown)=>{try{void Promise.resolve(ctx.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
 register({name:'search_reading_log',description:'Search the saved reading log and show matching books.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{const q=(input as {query?:unknown})?.query;if(typeof q!=='string'||q.length>500)throw Error('Cal una cerca de text de fins a 500 caràcters.');setStatus('all');setYear('all');setQuery(q);return books.filter(b=>normalize([b.title,b.author,b.summary,b.place].join(' ')).includes(normalize(q))).map(b=>({id:b.id,title:b.title,author:b.author,finishedOn:b.finishedOn}))}});
 register({name:'open_book_details',description:'Open a saved book to read its details or begin editing. Does not save changes.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{const b=books.find(b=>b.id===(input as {id?:unknown})?.id);if(!b)throw Error('Llibre no trobat.');setStartEditing(false);setActive(b);return {opened:b.id,title:b.title}}});
 return()=>lifecycle.abort()},[books]);
 const open=(b:Book,edit=false)=>{setStartEditing(edit);setActive(b)};
 function saved(book:Book){setBooks(bs=>{const found=bs.some(b=>b.id===book.id);return found?bs.map(b=>b.id===book.id?book:b):[...bs,book]});setActive(null);setMessage('Lectura desada.');setTimeout(()=>setMessage(''),5000)}
 function exportBooks(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),books},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='quadern-de-lectures-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const readCount=books.filter(b=>b.read).length;
 return <main className="app"><Tabs value={view} onValueChange={setView}><header className="topbar"><a className="brand" href="./llibres.html"><BookOpen size={25} aria-hidden="true"/><span>Quadern de lectures</span></a><TabsList className="view-switch" aria-label="Visualització"><TabsTrigger value="library"><Grid2X2/>Biblioteca</TabsTrigger><TabsTrigger value="diary"><BookOpen/>Diari</TabsTrigger></TabsList>{canEdit?<button className="primary" onClick={()=>open(blankBook(),true)}><Plus size={18}/>Afegir llibre</button>:<button className="primary" onClick={signIn}><LogIn size={17}/>{signedIn?'Compte del propietari':'Entra per editar'}</button>}</header>
 <section className="collection-heading"><div><p className="eyebrow">BIBLIOTECA PERSONAL</p><h1>{view==='library'?'Llibres llegits':'Diari de lectures'}</h1></div><p className="collection-count"><strong>{loaded?readCount:'—'}</strong> lectures acabades</p></section>
 <div className="tools"><label className="search"><Search size={19} aria-hidden="true"/><input aria-label="Cerca a la biblioteca" type="search" placeholder="Un títol, un autor, un record…" value={query} onChange={e=>setQuery(e.target.value)}/></label><Filter label="Filtra per estat" value={status} onChange={setStatus} options={[['read','Llegits'],['all','Tots els llibres'],['unread','Sense marcar com a llegits'],['pending','Edició per confirmar']]}/><Filter label="Any de lectura" value={year} onChange={setYear} options={[['all','Tots els anys'],...years.map(y=>[y,y] as [string,string])]}/><Filter label="Ordena els llibres" value={sort} onChange={setSort} options={[['recent','Més recents'],['oldest','Més antics'],['title','Títol A–Z']]}/></div>
 {error&&<div className="notice error" role="alert">{error} <button className="text-button" onClick={()=>void load()}>Torna a carregar</button><p className="small-note">Les lectures es carreguen del registre compartit. <a href={apiBase} target="_blank" rel="noreferrer">Obre el servei de dades ↗</a></p></div>}
 {message&&<p className="notice" role="status">{message}</p>}
 <div className="statusline" style={{marginTop:-12,marginBottom:24}}><span>{filtered.length} {filtered.length===1?'llibre':'llibres'}{status==='read'?' llegits':''}{year!=='all'?' · '+year:''}</span><span className="results-count" role="status">{error?'Sense connexió':!loaded?'Connectant amb el quadern…':coverProgress?'Cercant portades…':'Canvis sincronitzats'}</span></div>
 <TabsContent value="library"><div className="book-grid">{visible.map(b=><button className="book-card" key={b.id} onClick={()=>open(b)} aria-label={'Obre '+b.title}><Cover book={b} suggested={suggestions[b.id]}/><h2>{b.title}</h2><p>{b.author||'Autor pendent'}</p><span className="book-date">{b.read?dateLabel(b.finishedOn):'Lectura pendent'}<ArrowUpRight size={15} aria-hidden="true"/></span></button>)}</div></TabsContent>
 <TabsContent value="diary"><div className="diary">{visible.map((b,i)=>{const y=b.finishedOn.slice(0,4)||'Sense data';return <Fragment key={b.id}>{(i===0||visible[i-1].finishedOn.slice(0,4)!==b.finishedOn.slice(0,4))&&<h2 className="diary-year">{y}</h2>}<article className="diary-entry"><time>{b.read?dateLabel(b.finishedOn):'Lectura pendent'}<span>{b.place&&<><MapPin size={12} style={{display:'inline'}}/> {b.place}</>}</span></time><div className="diary-book"><button className="diary-title diary-thumb" aria-label={'Obre '+b.title} onClick={()=>open(b)}><Cover book={b} suggested={suggestions[b.id]}/></button><div><button className="diary-title" onClick={()=>open(b)}><h2>{b.title}</h2></button><p className="muted">{b.author}{b.publisher?' · '+b.publisher:''}</p><p style={{whiteSpace:'pre-wrap',marginTop:12}}>{b.summary||'Encara no hi ha cap record escrit.'}</p></div></div></article></Fragment>})}</div></TabsContent>
 {loaded&&!filtered.length&&<div className="empty"><BookOpen size={32} style={{margin:'0 auto 12px'}}/><p>No hi ha llibres amb aquests filtres.</p><button className="text-button" onClick={()=>{setQuery('');setYear('all');setStatus('all')}}>Mostra tots els llibres</button></div>}
 {limit<filtered.length&&<div style={{textAlign:'center',marginTop:35}}><button className="secondary" onClick={()=>setLimit(l=>l+24)}>Mostra’n més · {visible.length} de {filtered.length}</button></div>}
 </Tabs><footer><span>{books.length} títols · {books.filter(b=>b.summary).length} records escrits · <a href="https://openlibrary.org" target="_blank" rel="noreferrer">Open Library</a> i <a href="https://books.google.com" target="_blank" rel="noreferrer">Google Books</a></span><div className="actions"><button className="text-button" onClick={exportBooks} disabled={!loaded}><Download size={14}/>Exporta una còpia</button>{signedIn&&<button className="text-button" onClick={()=>void signOut().catch(e=>setError(e.message))}>Surt</button>}</div></footer>
 {active&&<Editor key={active.id} initial={active} canEdit={canEdit} onSaved={saved} onClose={()=>setActive(null)} suggested={suggestions[active.id]} startEditing={startEditing}/>}
 </main>
}
